### ISSUE TITLE
Display settings reverts without any warning 

### ISSUE THREAD

**Issue by SDD701** [pimvullers/elementary#234] opened 2023-04-05 06:30 UTC
When I change my display settings, there is no menu like "To accept this setting click accept or after 30 seconds it will be a rollback" so after changing it's always reverts after some time

**Comment by pimvullers** [comment] 2023-11-26 22:54
Cannot reproduce (I do get the pop-up). Can you please check with latest versions if you still experience the problem.

**Comment by pimvullers** [comment] 2024-01-18 15:15
Closing since no feedback received.

**Closed by pimvullers** 2024-01-18 15:15 UTC
